services:
  database:
    image: postgres:14-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: "TimMovieDatabase"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
  
  mvc:
    container_name: mvc
    build:
      dockerfile: Dockerfile
    ports:
      - '8080:80'
    depends_on:
      - database