services:
  database:
    image: postgres:14-alpine
    ports:
      - '54320:5432'
    environment:
      POSTGRES_DB: "SupportChatDatabase"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgrespw"
  
  rabbit-mq:
    image: rabbitmq:3.7-management
    ports:
      - "5672:5672"
      - "15672:15672"
        
  mongo:
    image: mongo
    ports:
      - 27017:27017
        
  minio:
    image: minio/minio
    command: server --console-address ":9001" /data/
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio_user
      MINIO_ROOT_PASSWORD: minio_password
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3

  redis:
    image: bitnami/redis
    ports:
      - '6379:6379'
    environment:
      REDIS_REPLICATION_MODE: 'master'
      ALLOW_EMPTY_PASSWORD: 'yes'