services:
  frontend:
    build: 
      context: client/chat
      dockerfile: Dockerfile
    ports:
      - '8080:80'
    depends_on:
      - backend

  backend:
    restart: always
    build:
      context: server/SupportChat
      dockerfile: SupportChat.Api/Dockerfile
    ports:
      - '8081:80'
    depends_on:
      - database

  database:
    image: postgres:14-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: "SupportChatDatabase"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"