services:
  frontend:
    build: 
      context: client/chat
      dockerfile: Dockerfile
    ports:
      - '8080:80'
    depends_on:
      - backend

  backend:
    build:
      context: server/SupportChat
      dockerfile: SupportChat.Api/Dockerfile
    ports:
      - '8081:80'
    depends_on:
      - database

  database:
    image: postgres:14-alpine

  rabbit-mq-relay:
    image: cloudamqp/websocket-tcp-relay
    ports:
      - '15670:15670'
    command:
      - '--upstream'
      - 'tcp://rabbit-mq:5672'
    depends_on:
      - rabbit-mq

  rabbit-mq:
    image: rabbitmq:3.7-management
    ports:
      - "5672:5672"
      - "8082:15672"