services:
  frontend:
    build:
      context: client/chat
      dockerfile: Dockerfile
    ports:
      - '8080:80'
    depends_on:
      - backend

  backend:
    restart: always
    build:
      context: server/SupportChat
      dockerfile: SupportChat.WebHost/Dockerfile
    ports:
      - '8081:80'
    depends_on:
      - database

  database:
    image: postgres:14-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: "SupportChatDatabase"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
  
  rabbit-mq:
    image: rabbitmq:3.7-management
    ports:
      - "5672:5672"
      - "8082:15672"
  
  listener:
    restart: always
    build:
      context: server/SupportChat
      dockerfile: SupportChat.RabbitMQListener/Dockerfile
    ports:
      - '8083:80'
    depends_on:
      - backend

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
